
.MODEL SMALL
.STACK 100H
.CODE
MAIN PROC
    
    MOV AH,1
    
    
    INT 21H
    MOV BL,AL
    SUB BL,48
    
    
    INT 21H
    SUB AL,48
    
    
    MUL BL   ; MULTIPLICATION FUNCTION FOR UNSIGN NUMBER
    AAM      ;ADJUST AFTER MULTIPLICATION MUST USED TO SHOW THE RESULT IN TWO DIGIT
    
    MOV CX,AX  ;AFTER MULTPLYING 2 BYTE WE GET A WORD=16 BIT. THAT IS STORED IN AX & WE ARE MOVING THAT INTO CX
    
    ADD CH,48
    ADD CL,48
    
    MOV AH,2  ; OUTPUT FUNCTION
    MOV DL,10
    INT 21H
    MOV DL,13
    INT 21H
    MOV DL,CH ;PRINT HIGHER BYTE
    INT 21H 
    
    
    MOV DL,CL  ;LOWER BYTE
    INT 21H
    
    
    
    EXIT:
    MOV AH,4CH
    INT 21H
    MAIN ENDP
END MAIN


